# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: samplesheet_writer
description: Write the samplesheet and id mappings CSV files from samplesheet rows of any repository
keywords:
  - samplesheet
  - CSV
  - metadata
components: []
input:
  - ch_rows:
      type: map
      description: >
        Ordered Groovy Map for each run, starting with sample, fastq_1 and fastq_2

  - mapping_fields:
      type: string
      description: >
        Comma-separated list of fields for id_mappings.csv

  - outdir:
      type: string
      description: >
        Output directory for samplesheet and mappings files

output:
  - samplesheet:
      type: file
      description: >
        Samplesheet CSV file with metadata for pipeline input
      pattern: "samplesheet.csv"

  - mappings:
      type: file
      description: >
        ID mappings CSV file with selected fields
      pattern: "id_mappings.csv"

authors:
  - "@maxulysse"
  - "@Tabea01"
